### ISSUE TITLE
Docker file needs to be updated

### ISSUE THREAD

**Issue by kamalnayant** [mmumshad/simple-webapp-flask#21]
Docker file needs to be updated. unable to install flask

**Comment by rathulal** [comment]
pip instllation is not working
  Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "setuptools/__init__.py", line 8, in <module>
        import _distutils_hack.override  # noqa: F401
      File "_distutils_hack/__init__.py", line 194
        f'spec_for_{name}',
                         ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-D4mQfh/setuptools/

**Comment by mmumshad** [comment]
Fixed in `8fd4478` — apologies for the long wait! 🙏
